### PR TITLE
web: two-stage build Dockerfile

### PR DESCRIPTION
**Pull request by 3nprob**
Reduces resulting image size from 1.39GB to 143MB.

### CODE REVIEW

**Comment by ellenhp** [comment]
Wow, that's a much bigger difference than I would have expected. I'll take a look at this sometime soon but I need to bring down the demo server to fully test it so I'll want to wait until my post falls off the front page of HN :)

**Comment by 3nprob** [comment]
Cheers, and I should add that I didn't fully test this myself yet - just did a quick diff at the resulting images.

BTW, what do you think of the prospect of changing base_url from file to either build-args or env-vars (could use `envusbst`)? That would also make it smoother to similarly parameterize the upstreams and resolver args (making this image useful outside of the compose setup)

**Comment by ellenhp** [comment]
I'm totally open to either of those changes, but I think I want to keep the Makefile logic to load the base url from a file. I don't have a good reason but I like this way of doing things over environment variables from the user's perspective. It fits more with the philosophy of dead-simple builds. Anything downstream of the Makefile could be changed though as long as it preserves existing functionality.

**Comment by 3nprob** [comment]
It's your call of course but on flip side:
With the current approach any change (port, upstream change, etc) will require a full image rebuild. Whereas making it to env-vars means that configuration can all be changed at run-time. Depending on the environment this runs in, that can become more of a hassle. We could still keep the currently hardcoded ones as defaults, of course.


Also consider if prebuilt images at some point will be shared through e.g. Docker Hub or quay.

**Comment by ellenhp** [comment]
That's true, I just hate environment variables. This will be necessary if the project grows to the point that it's feasible to use for large areas, but there will be a number of other architectural problems that will crop up. I deliberately did some things that don't scale just because they're easy for the time being.

My demo server is still getting hammered so in all likelihood I won't be able to test until tomorrow but I will get to this because saving a gigabyte in the web image is a big deal. :)

**Comment by 3nprob** [comment]
Just in case you're not aware, you can still set those through a single .env files and include that from the docker-compose yaml

Slightly OT to this PR but I'm happy to look at things like this to making things more scalable/reusable/easy for others to use and make some more PRs (for example I noted that the photon image currently includes and transforms the data in the image build step - it could be split up in two images where one transforms the dataset at runtime, and the output of that can then be mounted as a volume in the second one). I think it could lower the bars for others to run and contribute (and could improve quality of life for yourself as well if you're open for adapting).

But maybe hint with a reaction to this comment on if this is :+1: or :-1: :)

**Comment by ellenhp** [comment]
I would absolutely love contributions to help with docker config stuff! I think the concept for this project is sound in that this is a thing that the world deserves, but the implementation was literally thrown together in a week so I'm not married to anything except the idea that it should be easy for new users to bring up their own instances.

**Comment by ellenhp** [comment]
Could you remove the trailing `*` from the COPY statement? it appears to have strange behavior and removing it but keeping the trailing slash solves things. Otherwise LGTM.

**Comment by 3nprob** [comment]
ohdd, perhaps some difference between docker versions..
either way, fixed now.

**Comment by ellenhp** [comment]
Thank you for the contribution!!!

**Pull request merged**
